version: '3'

services:
  nginx:
    build: ./docker/nginx
    container_name: web-nginx
    ports:
      - "8012:80"
      - "8013:81"
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/conf.d/server1.conf:/etc/nginx/conf.d/server1.conf
      - ./server1:/usr/share/nginx/server1